<?php

declare(strict_types=1);

namespace OCA\Ticketcheck\Tests\Unit\AppInfo;

use PHPUnit\Framework\TestCase;
use ReflectionClass;

/**
 * Container-wide guard against \`occ upgrade\` / boot fatals from dependency-injection
 * arity drift. Auto-generated by scripts/sync-app-di-guard-tests.php — do not edit by hand;
 * re-run the sync script after changing Application.php factories.
 *
 * @see RepairStepDiRegistrationTest (repair steps in info.xml only)
 */
final class ServiceContainerDiRegistrationTest extends TestCase
{
	private const APP_NAMESPACE = 'OCA\\Ticketcheck';

	/**
	 * @return array<string, array{0: string, 1: int}>
	 */
	public static function registeredAppServices(): array
	{
		$source = self::applicationSource();
		$useMap = self::parseUseMap($source);

		$cases = [];
		foreach (self::parseRegisteredFactories($source) as $factory) {
			$fqcn = self::resolveClass($factory['constructed'], $useMap);
			if (!str_starts_with($fqcn, self::APP_NAMESPACE . '\\')) {
				continue;
			}
			// Console commands extend symfony/console; standalone CI stubs that parent in bootstrap.
			if (str_contains($fqcn, '\\Command\\')) {
				continue;
			}
			$cases[$fqcn] = [$fqcn, $factory['argCount']];
		}

		ksort($cases);
		return $cases;
	}

	/** @dataProvider registeredAppServices */
	public function testFactoryPassesEnoughConstructorArguments(string $fqcn, int $argsPassed): void
	{
		$this->assertTrue(class_exists($fqcn), $fqcn . ' is registered but cannot be autoloaded');

		$required = (new ReflectionClass($fqcn))->getConstructor()?->getNumberOfRequiredParameters() ?? 0;

		$this->assertGreaterThanOrEqual(
			$required,
			$argsPassed,
			sprintf(
				'%s requires %d constructor argument(s) but Application.php passes %d '
				. '(ArgumentCountError on boot/occ upgrade).',
				$fqcn,
				$required,
				$argsPassed,
			),
		);
	}

	public function testEveryExplicitFactoryIsParsed(): void
	{
		$source = self::applicationSource();
		$explicit = self::countExplicitFactories($source);
		$parsed = count(self::parseRegisteredFactories($source));

		$this->assertSame(
			$explicit,
			$parsed,
			sprintf(
				'Found %d registerService block(s) with explicit \`new\` factories but parsed %d; '
				. 'update the DI guard parser if Application.php registration style changed.',
				$explicit,
				$parsed,
			),
		);
	}

	private static function applicationSource(): string
	{
		$path = dirname(__DIR__, 3) . '/lib/AppInfo/Application.php';
		$source = file_get_contents($path);
		if ($source === false) {
			throw new \RuntimeException('Could not read Application.php at ' . $path);
		}
		return $source;
	}

	/** @return array<string, string> */
	private static function parseUseMap(string $source): array
	{
		$map = [];
		if (preg_match_all('/^\s*use\s+([A-Za-z0-9_\\\\]+)(?:\s+as\s+([A-Za-z0-9_]+))?\s*;/m', $source, $matches, PREG_SET_ORDER)) {
			foreach ($matches as $m) {
				$fqcn = trim($m[1], '\\');
				$pos = strrpos($fqcn, '\\');
				$short = $pos === false ? $fqcn : substr($fqcn, $pos + 1);
				$alias = $m[2] ?? $short;
				$map[$alias] = $fqcn;
			}
		}
		return $map;
	}

	/** @param array<string, string> $useMap */
	private static function resolveClass(string $ref, array $useMap): string
	{
		$ref = trim($ref);
		if (str_starts_with($ref, '\\')) {
			return ltrim($ref, '\\');
		}
		if (!str_contains($ref, '\\')) {
			return $useMap[$ref] ?? (self::APP_NAMESPACE . '\\AppInfo\\' . $ref);
		}
		$first = explode('\\', $ref, 2)[0];
		if (isset($useMap[$first])) {
			return $useMap[$first] . '\\' . explode('\\', $ref, 2)[1];
		}
		return $ref;
	}

	/** @return list<array{constructed: string, argCount: int}> */
	private static function parseRegisteredFactories(string $source): array
	{
		$results = [];
		$offset = 0;
		while (($pos = strpos($source, 'registerService(', $offset)) !== false) {
			$offset = $pos + 1;
			$blockEnd = self::findRegisterServiceBlockEnd($source, $pos);
			$block = substr($source, $pos, $blockEnd - $pos);

			if (!preg_match('/(?:return\s+|=>\s*)new\s+(\\\\?[A-Za-z0-9_\\\\]+)\s*\(/', $block, $m, PREG_OFFSET_CAPTURE)) {
				continue;
			}
			$constructed = $m[1][0];
			$openParen = $m[0][1] + strlen($m[0][0]) - 1;
			$inner = self::extractBalanced($block, $openParen);
			if ($inner === null) {
				continue;
			}
			$results[] = [
				'constructed' => $constructed,
				'argCount' => count(self::splitTopLevel($inner)),
			];
		}
		return $results;
	}

	private static function countExplicitFactories(string $source): int
	{
		$count = 0;
		$offset = 0;
		while (($pos = strpos($source, 'registerService(', $offset)) !== false) {
			$offset = $pos + 1;
			$blockEnd = self::findRegisterServiceBlockEnd($source, $pos);
			$block = substr($source, $pos, $blockEnd - $pos);
			if (preg_match('/(?:return\s+|=>\s*)new\s+/s', $block)) {
				$count++;
			}
		}
		return $count;
	}

	private static function findRegisterServiceBlockEnd(string $source, int $registerPos): int
	{
		$len = strlen($source);
		$depth = 0;
		$started = false;
		for ($i = $registerPos; $i < $len; $i++) {
			$ch = $source[$i];
			if ($ch === '(') {
				$depth++;
				$started = true;
				continue;
			}
			if ($ch === ')') {
				$depth--;
				if ($started && $depth === 0) {
					return $i + 1;
				}
			}
		}
		return $len;
	}

	private static function extractBalanced(string $source, int $openPos): ?string
	{
		$len = strlen($source);
		$depth = 0;
		$inner = '';
		$inSingle = false;
		$inDouble = false;
		for ($i = $openPos; $i < $len; $i++) {
			$ch = $source[$i];
			$prev = $i > 0 ? $source[$i - 1] : '';

			if ($inSingle) {
				if ($ch === "'" && $prev !== '\\') {
					$inSingle = false;
				}
				if ($depth >= 1) {
					$inner .= $ch;
				}
				continue;
			}
			if ($inDouble) {
				if ($ch === '"' && $prev !== '\\') {
					$inDouble = false;
				}
				if ($depth >= 1) {
					$inner .= $ch;
				}
				continue;
			}
			if ($ch === "'") {
				$inSingle = true;
				if ($depth >= 1) {
					$inner .= $ch;
				}
				continue;
			}
			if ($ch === '"') {
				$inDouble = true;
				if ($depth >= 1) {
					$inner .= $ch;
				}
				continue;
			}
			if ($ch === '(' || $ch === '[' || $ch === '{') {
				$depth++;
				if ($depth >= 2) {
					$inner .= $ch;
				}
				continue;
			}
			if ($ch === ')' || $ch === ']' || $ch === '}') {
				$depth--;
				if ($depth === 0) {
					return $inner;
				}
				$inner .= $ch;
				continue;
			}
			if ($depth >= 1) {
				$inner .= $ch;
			}
		}
		return null;
	}

	/** @return list<string> */
	private static function splitTopLevel(string $inner): array
	{
		$segments = [];
		$current = '';
		$depth = 0;
		$inSingle = false;
		$inDouble = false;
		$len = strlen($inner);
		for ($i = 0; $i < $len; $i++) {
			$ch = $inner[$i];
			$prev = $i > 0 ? $inner[$i - 1] : '';

			if ($inSingle) {
				$current .= $ch;
				if ($ch === "'" && $prev !== '\\') {
					$inSingle = false;
				}
				continue;
			}
			if ($inDouble) {
				$current .= $ch;
				if ($ch === '"' && $prev !== '\\') {
					$inDouble = false;
				}
				continue;
			}
			if ($ch === "'") {
				$inSingle = true;
				$current .= $ch;
				continue;
			}
			if ($ch === '"') {
				$inDouble = true;
				$current .= $ch;
				continue;
			}
			if ($ch === '(' || $ch === '[' || $ch === '{') {
				$depth++;
				$current .= $ch;
				continue;
			}
			if ($ch === ')' || $ch === ']' || $ch === '}') {
				$depth--;
				$current .= $ch;
				continue;
			}
			if ($ch === ',' && $depth === 0) {
				$segments[] = trim($current);
				$current = '';
				continue;
			}
			$current .= $ch;
		}
		if (trim($current) !== '') {
			$segments[] = trim($current);
		}
		return array_values(array_filter($segments, static fn (string $s): bool => $s !== ''));
	}
}
