<?php

declare(strict_types=1);

namespace OCA\Ticketcheck\Tests\Integration;

use Test\TestCase;

/**
 * Resolves every service registered in Application.php through the real Nextcloud
 * container (boot / occ upgrade path). Auto-generated by scripts/sync-app-di-guard-tests.php.
 */
class ContainerServiceResolutionIntegrationTest extends TestCase
{
	protected function setUp(): void
	{
		if (!class_exists(\OC::class) || !isset(\OC::$server)) {
			$this->markTestSkipped('Nextcloud is not bootstrapped (set NEXTCLOUD_ROOT or run inside Docker).');
		}
	}

	/**
	 * Resolves the concrete class built by each explicit factory (FQCN registrations
	 * and legacy string aliases such as 'ProjectService' → ProjectService::class).
	 *
	 * @return array<string, array{0: string}>
	 */
	public static function registeredServices(): array
	{
		$path = dirname(__DIR__, 2) . '/lib/AppInfo/Application.php';
		$source = file_get_contents($path);
		if ($source === false) {
			throw new \RuntimeException('Could not read Application.php at ' . $path);
		}
		$useMap = self::parseUseMap($source);

		$cases = [];
		$offset = 0;
		while (($pos = strpos($source, 'registerService(', $offset)) !== false) {
			$offset = $pos + 1;
			$blockEnd = self::findRegisterServiceBlockEnd($source, $pos);
			$block = substr($source, $pos, $blockEnd - $pos);
			$rest = substr($source, $pos + strlen('registerService('));

			$resolveFqcn = null;
			if (preg_match('/^\s*(\\\\?[A-Za-z0-9_\\\\]+)::class/', $rest, $m)) {
				$resolveFqcn = self::resolveClass(ltrim($m[1], '\\'), $useMap);
			} elseif (preg_match("/^\s*'([^']+)'/", $rest, $m)) {
				$alias = $m[1];
				if (preg_match('/(?:return\s+|=>\s*)new\s+(\\\\?[A-Za-z0-9_\\\\]+)\s*\(/', $block, $nm)) {
					$resolveFqcn = self::resolveClass($nm[1], $useMap);
				} else {
					$resolveFqcn = self::resolveClass($alias, $useMap);
				}
			}

			if ($resolveFqcn === null || !preg_match('/(?:return\s+|=>\s*)new\s+/s', $block)) {
				continue;
			}
			$cases[$resolveFqcn] = [$resolveFqcn];
		}
		ksort($cases);
		return $cases;
	}

	/** @dataProvider registeredServices */
	public function testServiceResolvesFromContainer(string $fqcn): void
	{
		$service = \OC::$server->get($fqcn);
		$this->assertInstanceOf($fqcn, $service, $fqcn . ' could not be resolved from the container');
	}

	private static function findRegisterServiceBlockEnd(string $source, int $registerPos): int
	{
		$len = strlen($source);
		$depth = 0;
		$started = false;
		for ($i = $registerPos; $i < $len; $i++) {
			$ch = $source[$i];
			if ($ch === '(') {
				$depth++;
				$started = true;
				continue;
			}
			if ($ch === ')') {
				$depth--;
				if ($started && $depth === 0) {
					return $i + 1;
				}
			}
		}
		return $len;
	}

	/** @return array<string, string> */
	private static function parseUseMap(string $source): array
	{
		$map = [];
		if (preg_match_all('/^\s*use\s+([A-Za-z0-9_\\\\]+)(?:\s+as\s+([A-Za-z0-9_]+))?\s*;/m', $source, $matches, PREG_SET_ORDER)) {
			foreach ($matches as $m) {
				$fqcn = trim($m[1], '\\');
				$pos = strrpos($fqcn, '\\');
				$short = $pos === false ? $fqcn : substr($fqcn, $pos + 1);
				$alias = $m[2] ?? $short;
				$map[$alias] = $fqcn;
			}
		}
		return $map;
	}

	/** @param array<string, string> $useMap */
	private static function resolveClass(string $ref, array $useMap): string
	{
		$ref = trim($ref);
		if (str_starts_with($ref, '\\')) {
			return ltrim($ref, '\\');
		}
		if (!str_contains($ref, '\\')) {
			return $useMap[$ref] ?? ('OCA\\Ticketcheck\\AppInfo\\' . $ref);
		}
		$first = explode('\\', $ref, 2)[0];
		if (isset($useMap[$first])) {
			return $useMap[$first] . '\\' . explode('\\', $ref, 2)[1];
		}
		return $ref;
	}
}
