<?php

declare(strict_types=1);

namespace OCA\Ticketcheck\Seed;

use OCA\Ticketcheck\Db\HelpdeskCustomer;
use OCA\Ticketcheck\Db\HelpdeskCustomerMapper;
use OCA\Ticketcheck\Db\HelpdeskProject;
use OCA\Ticketcheck\Db\HelpdeskProjectMapper;
use OCA\Ticketcheck\Db\Ticket;
use OCA\Ticketcheck\Db\TicketMapper;
use OCP\AppFramework\Db\DoesNotExistException;
use OCP\IDBConnection;
use OCP\IUserManager;
use Psr\Log\LoggerInterface;

/**
 * Seeds the internal Prototype Fund backlog (80 NEXTICK tickets) into one helpdesk project.
 *
 * Data: lib/Seed/data/prototype-fund-backlog.json (generated by scripts/generate-backlog-issues-md.py)
 */
class PrototypeFundBacklogSeeder
{
    public const PROJECT_NAME = 'NEXTICK — Prototype Fund Backlog (intern)';

    private const SEED_FILE = __DIR__ . '/data/prototype-fund-backlog.json';

    /** @var array<string, string> */
    private array $assigneeMap = [
        'Alex' => 'alex',
        'Lara' => 'lara',
        'Hauke' => 'hauke',
        'Team' => '',
    ];

    public function __construct(
        private readonly IDBConnection $db,
        private readonly HelpdeskProjectMapper $projectMapper,
        private readonly HelpdeskCustomerMapper $customerMapper,
        private readonly TicketMapper $ticketMapper,
        private readonly IUserManager $userManager,
        private readonly LoggerInterface $logger,
    ) {
    }

    /**
     * @param array<string, string> $assigneeOverrides uid keys: alex, lara, hauke (optional)
     */
    public function setAssigneeMap(array $assigneeOverrides): void
    {
        foreach ($assigneeOverrides as $key => $uid) {
            if ($uid === '') {
                continue;
            }
            $label = match (strtolower($key)) {
                'alex' => 'Alex',
                'lara' => 'Lara',
                'hauke' => 'Hauke',
                default => ucfirst($key),
            };
            $this->assigneeMap[$label] = $uid;
        }
        $this->assigneeMap['Team'] = $assigneeOverrides['team'] ?? $assigneeOverrides['actor'] ?? $this->assigneeMap['Team'];
    }

    /**
     * @return array{created: int, skipped: int, project_id: int, customer_id: int|null}
     */
    public function seed(string $actorUserId, bool $force = false, bool $dryRun = false): array
    {
        $payload = $this->loadPayload();
        $this->assigneeMap['Team'] = $this->assigneeMap['Team'] !== '' ? $this->assigneeMap['Team'] : $actorUserId;

        if ($dryRun) {
            return [
                'created' => count($payload['issues']),
                'skipped' => 0,
                'project_id' => 0,
                'customer_id' => null,
            ];
        }

        $this->db->beginTransaction();
        try {
            $customerId = $this->ensureCustomer($payload['customer_name'], $actorUserId);
            $project = $this->ensureProject(
                $payload['project_name'],
                $payload['project_description'],
                $customerId,
                $actorUserId,
                $force,
            );
            $projectId = $project->getId();

            if ($force) {
                $this->deleteSeedTickets($projectId);
            }

            $created = 0;
            $skipped = 0;
            foreach ($payload['issues'] as $row) {
                $ticketNumber = (string)$row['ticket_number'];
                if (!$force && $this->ticketExists($ticketNumber)) {
                    $skipped++;
                    continue;
                }
                $this->insertTicket($row, $projectId, $customerId, $payload['customer_name'], $actorUserId);
                $created++;
            }

            $this->db->commit();

            return [
                'created' => $created,
                'skipped' => $skipped,
                'project_id' => $projectId,
                'customer_id' => $customerId,
            ];
        } catch (\Throwable $e) {
            $this->db->rollBack();
            $this->logger->error('Prototype Fund backlog seed failed: ' . $e->getMessage(), ['exception' => $e]);
            throw $e;
        }
    }

    /**
     * @return array<string, mixed>
     */
    private function loadPayload(): array
    {
        if (!is_readable(self::SEED_FILE)) {
            throw new \RuntimeException(
                'Seed file missing. Run: python3 apps/ticketcheck/scripts/generate-backlog-issues-md.py'
            );
        }
        $raw = file_get_contents(self::SEED_FILE);
        if ($raw === false) {
            throw new \RuntimeException('Could not read seed file: ' . self::SEED_FILE);
        }
        $data = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        if (!isset($data['issues']) || !is_array($data['issues'])) {
            throw new \RuntimeException('Invalid seed file: missing issues array');
        }

        return $data;
    }

    private function ensureCustomer(string $name, string $actorUserId): int
    {
        $qb = $this->db->getQueryBuilder();
        $qb->select('id')
            ->from('helpdesk_customers')
            ->where($qb->expr()->eq('name', $qb->createNamedParameter($name)));
        $result = $qb->executeQuery();
        $id = $result->fetchOne();
        $result->closeCursor();
        if ($id !== false) {
            return (int)$id;
        }

        $customer = new HelpdeskCustomer();
        $customer->setName($name);
        $customer->setEmail(null);
        $now = new \DateTime();
        $customer->setCreatedAt($now);
        $customer->setUpdatedAt($now);
        $customer->setCreatedBy($actorUserId);
        $inserted = $this->customerMapper->insert($customer);

        return $inserted->getId();
    }

    private function ensureProject(
        string $name,
        string $description,
        ?int $customerId,
        string $actorUserId,
        bool $force,
    ): HelpdeskProject {
        $existing = $this->findProjectByName($name);
        if ($existing !== null) {
            if ($force) {
                return $existing;
            }

            return $existing;
        }

        $project = new HelpdeskProject();
        $project->setName($name);
        $project->setDescription($description);
        $project->setCustomerId($customerId);
        $project->setStatus('active');
        $project->setActive(true);
        $project->setCreatedAt(new \DateTime());
        $project->setUpdatedAt(new \DateTime());
        $project->setCreatedBy($actorUserId);

        return $this->projectMapper->insert($project);
    }

    private function findProjectByName(string $name): ?HelpdeskProject
    {
        $qb = $this->db->getQueryBuilder();
        $qb->select('id')
            ->from('helpdesk_projects')
            ->where($qb->expr()->eq('name', $qb->createNamedParameter($name)));
        $result = $qb->executeQuery();
        $id = $result->fetchOne();
        $result->closeCursor();
        if ($id === false) {
            return null;
        }

        return $this->projectMapper->find((int)$id);
    }

    private function deleteSeedTickets(int $projectId): void
    {
        $tickets = $this->ticketMapper->findByProjectId($projectId, 500);
        foreach ($tickets as $ticket) {
            if (!str_starts_with($ticket->getTicketNumber(), 'NEXTICK-')) {
                continue;
            }
            $this->ticketMapper->delete($ticket);
        }
    }

    private function ticketExists(string $ticketNumber): bool
    {
        try {
            $this->ticketMapper->findByTicketNumber($ticketNumber);

            return true;
        } catch (DoesNotExistException) {
            return false;
        }
    }

    /**
     * @param array<string, mixed> $row
     */
    private function insertTicket(
        array $row,
        int $projectId,
        ?int $customerId,
        string $customerName,
        string $actorUserId,
    ): void {
        $ticket = new Ticket();
        $ticket->setTicketNumber((string)$row['ticket_number']);
        $ticket->setTitle($this->formatTicketTitle($row));
        $ticket->setDescription((string)$row['description']);
        $ticket->setCustomerId($customerId);
        $ticket->setCustomerName($customerName);
        $ticket->setCustomerEmail('intern@nextick.invalid');
        $ticket->setProjectId($projectId);
        $ticket->setCategory($this->mapCategory($row));
        $ticket->setPriority($this->mapPriority($row));
        $ticket->setStatus($this->mapStatus($row));
        $ticket->setAssignedTo($this->resolveAssignee((string)$row['assignee']));
        $ticket->setCreatedBy($actorUserId);
        $ticket->setCreatedByGuest(false);

        [$createdAt, $closedAt] = $this->resolveDates($row);
        $ticket->setCreatedAt($createdAt);
        $ticket->setUpdatedAt($closedAt ?? $createdAt);
        $ticket->setClosedAt($closedAt);
        $this->applySlaDates($ticket, $createdAt);

        $errors = $ticket->validate();
        if ($errors !== []) {
            throw new \RuntimeException(
                'Validation failed for ' . $ticket->getTicketNumber() . ': ' . implode(', ', $errors)
            );
        }

        $this->ticketMapper->insert($ticket);
    }

    /**
     * @param array<string, mixed> $row
     */
    private function formatTicketTitle(array $row): string
    {
        $n = (int)$row['n'];
        $title = (string)$row['title'];

        return sprintf('NEXTICK-%03d · %s', $n, $title);
    }

    /**
     * @param array<string, mixed> $row
     */
    private function mapCategory(array $row): string
    {
        $labels = $row['labels'] ?? [];
        if (!is_array($labels)) {
            return Ticket::CATEGORY_GENERAL;
        }
        if (in_array('security', $labels, true) || ($row['type'] ?? '') === 'Security') {
            return Ticket::CATEGORY_TECHNICAL;
        }
        if (in_array('ux', $labels, true) || in_array('pilot-feedback', $labels, true)) {
            return Ticket::CATEGORY_FEATURE;
        }
        if (in_array('docs', $labels, true)) {
            return Ticket::CATEGORY_GENERAL;
        }
        if (($row['type'] ?? '') === 'Bug / Qualität') {
            return Ticket::CATEGORY_BUG;
        }
        if (($row['type'] ?? '') === 'Epic / Meilenstein') {
            return Ticket::CATEGORY_FEATURE;
        }

        return Ticket::CATEGORY_TECHNICAL;
    }

    /**
     * @param array<string, mixed> $row
     */
    private function mapPriority(array $row): string
    {
        $prio = (string)($row['priority'] ?? 'Must');
        if (str_contains($prio, 'Won')) {
            return Ticket::PRIORITY_LOW;
        }
        if (str_contains($prio, 'Could')) {
            return Ticket::PRIORITY_LOW;
        }
        if (str_contains($prio, 'Should')) {
            return Ticket::PRIORITY_NORMAL;
        }
        if (($row['milestone'] ?? '') !== '' || in_array('blocker', $row['labels'] ?? [], true)) {
            return Ticket::PRIORITY_HIGH;
        }

        return Ticket::PRIORITY_NORMAL;
    }

    /**
     * @param array<string, mixed> $row
     */
    private function mapStatus(array $row): string
    {
        $lifecycle = (string)($row['lifecycle'] ?? 'done');
        return match ($lifecycle) {
            'done' => Ticket::STATUS_DONE,
            'post_release' => Ticket::STATUS_WAITING,
            default => Ticket::STATUS_IN_PROGRESS,
        };
    }

    private function resolveAssignee(string $label): ?string
    {
        $uid = $this->assigneeMap[$label] ?? '';
        if ($uid === '') {
            return null;
        }
        if ($this->userManager->get($uid) === null) {
            $this->logger->warning('Assignee UID not found, ticket left unassigned', [
                'label' => $label,
                'uid' => $uid,
            ]);

            return null;
        }

        return $uid;
    }

    /**
     * @param array<string, mixed> $row
     * @return array{\DateTime, \DateTime|null}
     */
    private function resolveDates(array $row): array
    {
        $doneRaw = $row['done_at'] ?? null;
        $closedAt = null;
        if (is_string($doneRaw) && $doneRaw !== '') {
            $parsed = \DateTime::createFromFormat('d.m.Y', $doneRaw);
            $closedAt = $parsed instanceof \DateTime ? $parsed : null;
        }
        $createdAt = $closedAt !== null
            ? (clone $closedAt)->modify('-14 days')
            : $this->defaultCreatedAt((int)$row['n']);

        return [$createdAt, $closedAt];
    }

    private function defaultCreatedAt(int $issueNumber): \DateTime
    {
        if ($issueNumber <= 8) {
            return new \DateTime('2026-06-08 10:00:00');
        }
        if ($issueNumber <= 22) {
            return new \DateTime('2026-06-22 10:00:00');
        }
        if ($issueNumber <= 33) {
            return new \DateTime('2026-07-20 10:00:00');
        }
        if ($issueNumber <= 44) {
            return new \DateTime('2026-08-17 10:00:00');
        }
        if ($issueNumber <= 51) {
            return new \DateTime('2026-09-14 10:00:00');
        }
        if ($issueNumber <= 60) {
            return new \DateTime('2026-09-28 10:00:00');
        }
        if ($issueNumber <= 70) {
            return new \DateTime('2026-10-12 10:00:00');
        }
        if ($issueNumber <= 77) {
            return new \DateTime('2026-11-09 10:00:00');
        }

        return new \DateTime('2026-11-23 10:00:00');
    }

    private function applySlaDates(Ticket $ticket, \DateTime $base): void
    {
        $hours = match ($ticket->getPriority()) {
            Ticket::PRIORITY_URGENT => [4, 24],
            Ticket::PRIORITY_HIGH => [8, 48],
            Ticket::PRIORITY_LOW => [48, 240],
            default => [24, 120],
        };
        $ticket->setSlaResponseDue((clone $base)->modify('+' . $hours[0] . ' hours'));
        $ticket->setSlaResolutionDue((clone $base)->modify('+' . $hours[1] . ' hours'));
    }
}
